### ISSUE TITLE
networkx

### ISSUE THREAD

**Issue by colebuckleyy** [for-just-we/CppCodeAnalyzer#2]
如果我想将 CPG 图传输到 networkx 中，我应该使用 ast 节点属性来连接内容并将内容用作节点，还是将它们作为单个节点的属性加载

**Comment by for-just-we** [comment]
> 

networkx我还没用到，不过你可以试试把AST结点类型（调用 `ASTNode.getTypeAsString()`）用作graph结点属性，然后 `codeStr` 用做graph结点内容。

**Comment by for-just-we** [comment]
> 如果我想将 CPG 图传输到 networkx 中，我应该使用 ast 节点属性来连接内容并将内容用作节点，还是将它们作为单个节点的属性加载

networkx我还没用到，不过你可以试试把AST结点类型（调用 `ASTNode.getTypeAsString()`）用作graph结点属性，然后 `codeStr` 用做graph结点内容。

**Comment by colebuckleyy** [comment]
谢谢你, 我会试试这个
